// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVy7YJI1NeJPB-BMgA7nN9T-itE6iM0Bs',
    appId: '1:380796197825:web:4b3c410420aa1efa596d40',
    messagingSenderId: '380796197825',
    projectId: 'zodo-ai-dr',
    authDomain: 'zodo-ai-dr.firebaseapp.com',
    storageBucket: 'zodo-ai-dr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkLqRymHcmS0b6Wb3v7XOJoZiu8lFeUOo',
    appId: '1:380796197825:android:22ac882bfd565480596d40',
    messagingSenderId: '380796197825',
    projectId: 'zodo-ai-dr',
    storageBucket: 'zodo-ai-dr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoGY_44cC0OPjoq-TiOWFodmyVoiUeWn4',
    appId: '1:380796197825:ios:865e18d568ce8389596d40',
    messagingSenderId: '380796197825',
    projectId: 'zodo-ai-dr',
    storageBucket: 'zodo-ai-dr.firebasestorage.app',
    iosBundleId: 'com.example.zodoDr',
  );
}
